M48
; DRILL file {KiCad 7.0.5} date Wed Aug 20 16:23:00 2025
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-20T16:23:00-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X92.742Y-87.941
X92.742Y-108.541
X157.742Y-92.902
X157.742Y-111.952
T0
M30
