M48
; DRILL file {KiCad 7.0.5} date Mon Jan 22 10:56:54 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-22T10:56:54-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X95.235Y-87.447
X95.235Y-108.977
X138.595Y-102.737
X145.305Y-85.267
T0
M30
