M48
; DRILL file {KiCad 7.0.8} date Thu Jan  4 12:02:29 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-04T12:02:29-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X102.38Y-82.885
X102.38Y-85.425
X102.38Y-87.965
T2
X94.44Y-108.51
X94.48Y-64.01
X163.38Y-63.91
X163.38Y-95.81
T0
M30
